### ISSUE TITLE
Allow different sizes for bastion height and width

### ISSUE THREAD

**Issue by AngrySoundTech** [CivMC/Bastion#6]
Currently, we only support one `effectRadius:` for the width of a bastion.

Proposed config example after changes:

```yml
bastion:
  # A cube 
  bastion_1:
    range: 5

  # A rectangular cuboid
  bastion_2:
    range:
      height: 10
      width: 5
 ```

This has a "sister" ticket of https://github.com/CivMC/JukeAlert/issues/6, and these changes make the configs align.
